# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
# fos_ck_editor:
#     configs:
#         my_config:
#             toolbar: standard
fos_ck_editor:
    configs:
        my_config:
            uiColor: '#ffffff'
            # height: 500 # Hauteur de l'éditeur
            # width: 1000 # Largeur de l'éditeur
            font_style: 'Inclusive Sans'
            toolbar:
            - {
                    name: "styles",
                    items:
                        [
                            "Bold",
                            "Italic",
                            "Underline",
                            "Blockquote",
                            "-",
                            "Link",
                            "-",
                            "RemoveFormat",
                            "NumberedList",
                            "BulletedList",
                            "-",
                            "-",
                            "JustifyLeft",
                            "JustifyCenter",
                            "JustifyRight",
                            "JustifyBlock",
                            "-",
                            "-",
                            "TextColor",
                            "BGColor",
                            "HorizontalRule",
                            "-",
                            "FontSize",
                        ]
                }
            