vich_uploader:
   db_driver: orm

   metadata:
      type : attribute

   mappings:
      image_publication:
         uri_prefix: public/images/publication
         upload_destination: '%kernel.project_dir%/public/images/publication'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      image_commentaire:
         uri_prefix: public/images/commentaire
         upload_destination: '%kernel.project_dir%/public/images/commentaire'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      
